;;; readline-complete-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from readline-complete.el

(autoload 'ac-rlc-setup-sources "readline-complete" "\
Add me to shell-mode-hook!")
(autoload 'ac-rlc-prefix-shell-dispatcher "readline-complete")
(eval-after-load 'auto-complete '(eval '(ac-define-source shell '((candidates . rlc-candidates) (prefix . ac-rlc-prefix-shell-dispatcher) (requires . 0)))))
(autoload 'company-readline "readline-complete" "\
`company-mode' back-end using `readline-complete'.

(fn COMMAND &optional ARG &rest IGNORE)" t)
(register-definition-prefixes "readline-complete" '("ac-" "rlc-"))

;;; End of scraped data

(provide 'readline-complete-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; readline-complete-autoloads.el ends here
