;;; cursory-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cursory.el

(autoload 'cursory-set-preset "cursory" "\
Set cursor preset associated with STYLE.

STYLE is a symbol that represents the car of a list in
`cursory-presets'.

With optional LOCAL as a prefix argument, set the
`cursory-presets' only for the current buffer.  This does not
cover the `blink-cursor-mode', which is always global.

(fn STYLE &optional LOCAL)" t)
(autoload 'cursory-store-latest-preset "cursory" "\
Write latest cursor state to `cursory-latest-state-file'.
Can be assigned to `kill-emacs-hook'.")
(autoload 'cursory-restore-latest-preset "cursory" "\
Restore latest cursor style.")
(register-definition-prefixes "cursory" '("cursory-"))

;;; End of scraped data

(provide 'cursory-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cursory-autoloads.el ends here
